projeto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.home, name="home"),
    path('recipes/category/<int:category_id>/',
         views.category, name="category"),
    path('recipes/<int:id>/', views.recipes, name="recipe"),

]

recipes/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField()
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servigs_unit = models.CharField(max_length=65)
    preparation_step = models.TextField()
    preparation_step_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True, default=None,
    )
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.title

recipes/views.py
from django.shortcuts import render

from recipes.models import Recipe
from utils.recipe.factory import make_recipe


def home(request):
    recipes = Recipe.objects.all().order_by('-id').filter(is_published=True)
    return render(request, 'recipes/pages/home.html', context={
        'recipes': recipes,
    })


def category(request, category_id):
    recipes = Recipe.objects.filter(
        category__id=category_id,
        is_published=True
    ).order_by('-id')
    return render(request, 'recipes/pages/category.html', context={
        'recipes': recipes,
    })


def recipes(request, id):
    return render(request, 'recipes/pages/recipe-view.html', context={
        'recipe': make_recipe(),
        'is_detail_page': True,
    })

recipes/templates/recipes/pages/category.html
{% extends 'global/base.html' %}

{% block title %}Category{% endblock title %}Home

{% block content %}
<div class="main-content main-content-list container">
    {% for recipe in recipes %}
    {% include 'recipes/partials/recipe_card.html' %}
    {% endfor %}
</div>
{% endblock content %}

recipes/templates/recipes/pages/home.html
{% extends 'global/base.html' %}

{% block title %}Home{% endblock title %}Home

{% block content %}
<div class="main-content main-content-list container">
    {% for recipe in recipes %}
    {% include 'recipes/partials/recipe_card.html' %}
    {% endfor %}
</div>
{% endblock content %}

recipes/templates/recipes/pages/recipe-view.html
{% extends 'global/base.html' %}

{% block title %}Alterar{% endblock title %}Alterar

{% block content %}
<main class="main-content-container">
    <div class="main-content main-content-detail container">
        {% include 'recipes/partials/recipe_card.html' %}
    </div>
</main>
{% endblock content %}

recipes/templates/recipes/partials/footer.html
<footer class="main-footer">
    <div class="developer">
      <a href="https://github.com/Gabriel-S-Santos" target="_blank" rel="noreferrer noopener">By Gabriel Santos</a>
    </div>
  
    <div class="powered">
      <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>
  </footer>

recipes/templates/recipes/partials/head.html
{% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/fontawesome.min.css"
        integrity="sha512-RvQxwf+3zJuNwl4e0sZjQeX7kUa3o82bDETpgVCH2RiwYSZVDdFJ7N/woNigN/ldyOOoKw8584jM4plQdt8bhA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/brands.min.css"
        integrity="sha512-+oRH6u1nDGSm3hH8poU85YFIVTdSnS2f+texdPGrURaJh8hzmhMiZrQth6l56P4ZQmxeZzd2DqVEMqQoJ8J89A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/solid.min.css"
        integrity="sha512-uj2QCZdpo8PSbRGL/g5mXek6HM/APd7k/B5Hx/rkVFPNOxAQMXD+t+bG4Zv8OAdUpydZTU3UHmyjjiHv2Ww0PA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">

recipes/templates/recipes/partials/header.html
<header class="main-header-container">
    <div class="main_header container">
        <a class="main-logo" href="{% url 'recipes:home' %}">
            <h1>
                <i class="fa-sharp fa-solid fa-utensils main-logo-icon"></i>
                <span class="main-logo-text">Recipes</span>
            </h1>
        </a>
    </div>
</header>

recipes/templates/recipes/partials/recipe_card.html
<div class="recipe recipe-list-item">
    <div class="recipe-cover">
        <a href="{% url 'recipes:recipe' recipe.id %}">
        <img src="{{recipe.cover.url}}" alt="Temporario">
        </a>
    </div>

    <div class="recipe-title-container">
        <a href="{% url 'recipes:recipe' recipe.id %}">
        <h2 class="recipe-title">{{ recipe.title }}</h2>
        </a>
    </div>

    <div class="recipe-author">
        <span class="recipe-author-item">
            <i class="fas fa-user"></i>
            {% if recipe.author.first_name %}
                {{ recipe.author.first_name }} {{ recipe.author.last_name }}
            {% else %}
                {{ recipe.author.username }}
            {% endif %}
        </span>
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ recipe.created_at|date:"d/m/Y" }}
        </span>
        <span class="recipe-author-item">
            {% if recipe.category is not None %}
            <a href="{% url 'recipes:category' recipe.category.id %}">
                <i class="fas fa-layer-group"></i>
                <span>{{ recipe.category.name }}</span>
            </a>
            {% endif %}
        </span>
    </div>

    <div class="recipe-content">
        <p>{{ recipe.description }}</p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                {{recipe.preparation_time}} {{recipe.preparation_time_unit}}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">
                {{recipe.servings}} {{recipe.servings_unit}}
            </div>
        </div>
    </div>

    {% if is_detail_page is not True %}
    <footer class="recipe-footer">
        <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:recipe' recipe.id %}">
            <i class="fas fa-eye"></i>
            <span>ver mais...</span>
        </a>
    </footer>
    {% endif %}

    {% if is_detail_page is True %}
    <div class="preparation-steps">
       {{ recipe.preparation_steps|linebreaksbr }}
    </div>
    {% endif %}

</div>

recipes/templates/recipes/partials/search.html
{% if is_detail_page is not True %}
<div class="search-container">
    <div class="container">
        <form action="" class="search-form">
            <input type="search" class="search-input" name="q">
            <button type="submit" class="search-btn"><i class="fas fa-search"></i></button>
        </form>
    </div>
</div>
{% endif %}

{% if is_detail_page is True %}
<div class="spacing-detail"></div>
{% endif %}